### ISSUE TITLE
Mapbox: Classic styles are no longer supported

### ISSUE THREAD

**Issue by itsazzad** [Project-OSRM/osrm-frontend#336] opened 2021-03-08 12:17 UTC
2686@2x.png:1 GET https://api.mapbox.com/v4/mapbox.streets/13/4394/2686@2x.png?access_token=<access_token> 410 (Gone)

> {"message":"Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"}

After following https://hub.docker.com/r/osrm/osrm-backend/ I am getting the issue in the frontend.
![Screen Shot 2021-03-08 at 6 22 30 PM](https://user-images.githubusercontent.com/54909/110320999-4ab90f80-803b-11eb-8b86-d00c2d2a1d24.png)

**Comment by madmath03** [comment] 2021-03-15 14:40
Duplicate of #329

**Comment by mjjbell** [comment] 2021-03-15 23:17
Fixed by #331

**Closed as completed by mjjbell** 2021-03-15 23:17 UTC
